DROP TABLE IF EXISTS  questions;


CREATE TABLE questions(
  id SERIAL PRIMARY KEY,
  first VARCHAR,
  second VARCHAR,
  answer VARCHAR,
  trans VARCHAR,
  gender VARCHAR
);

INSERT INTO questions (first, answer, second, trans, gender) VALUES 
('Das Ticket ist', 'bis', 'Sonntag gültig', 'The ticket is valid until Sunday', 'a'),
('Der Spielplatz ist für Kinder', 'bis', '10 Jahre', 'The playground is for children up to 10 years old', 'a'),
('Das Freibad ist von April', 'bis', 'September geöffnet', 'The outdoor pool is open from April to September', 'a'),
('Ich schwimme', 'durch', 'den Fluss', 'I swim across the river', 'a'),
('Sie laufen', 'durch', 'das Haus', 'They run through the house', 'a'),
('Die Katze springt',  'durch',  'das Fenster',  'The cat jumps through the window', 'a'),
('Sie geht die Straße', 'entlang', 'nach Norden', 'She walks north along the street', 'a'),
('Du solltest', 'entlang', 'des Kanawegs laufen', 'You should run along the canal path', 'a'), 
('Heute fließt der Fluss', 'entlang', 'der Südseite des Tals', 'Today, the river flows along the southern side of the valley', 'a'),
('Ich habe etwas', 'für', 'den Mann', 'I have something for the man', 'a'),
('Ich arbeite nur', 'für', 'Geld', 'I just work for the money', 'a'),
('Er kauft einen Hotdog', 'für', 'seine Tochter', 'He buys a hotdog for his daughter', 'a'),
('Das Herrenhaus ist', 'gegen', '200 Jahre alt', 'The manor house is about 200 years old', 'a'),
('Wir kommen', 'gegen', 'Mittag an', 'We arrive about noon', 'a'),
('Das Auto fuhr',  'gegen',  'den Baum',  'The car hit the tree', 'a'),
('Sie kommt', 'ohne', 'die Kinder', 'She comes without the children', 'a'),
('Er verlässt sein Zuhause', 'ohne', 'seine Tasche', 'a'),
('Oma kann', 'ohne', 'Brille nicht lesen', 'Grandma can’t read without her glasses', 'a'),
('Er bittet',  'um',  'die Adresse', 'He asks for the address', 'a'),
('Die Familie sitzt',  'um',  'den Tisch',  'The family is sitting round the table', 'a'),
('Ich werde', 'um', 'Mitternacht nach Hause kommen', 'a'),
('Die Kinder weinen', 'um', 'ihre Mutter', 'The children cry for their mother', 'a'),
('Er kümmert sich', 'um', 'seine kranke Frau', 'He cares for his sick wife', 'a'),
('Ich hänge das Bild','an', 'die Wand', 'I hang the picture on the wall'), 
('Das Bild hängt','an', 'der Wand', 'The picture is hanging on the wall'),
('Das Rathaus liegt', 'am', 'Marktplatz', 'The townhall is in the marketplace'),
('Wir fahren', 'ans', 'Meer', 'We are driving to the sea'),
('Ich habe mich', 'beim', 'Skifahren verletzt', 'I injured myself while skiing'),
( 'Ich gehe jetzt',  'ins',  'Kino',  'I am going to the cinema now'),
(' ',  'Im', 'letzten Sommer war es hier sehr heiß',  'Last summer, it was very hot here'),
( 'Ich habe das',  'vom',  'Chef gehört',  'I heard that from the boss'),
('Ich gehe jetzt',  'zur',  'Schule',  'I am going to school now'),
( 'Ich gehe jetzt',  'zum',  'Supermarkt',  'I am going to the supermarket now'),
( 'Ich wohne',  'in',  'Berlin',  'I live in Berlin'),
( 'Ich bin gerade',  'im',  'Büro',  'I am in the office right now'),
( 'Ich gehe jetzt',  'ins',  'Büro',  'I am going to the office now'),
( 'Ich wohne',  'in',  'der Schweiz',  'I live in Switzerland'),
( 'Ich wohne',  'im',  'Schwarzwald',  'I live in the Black Forest'),
( 'Ich fahre',  'in',  'die Schweiz',  'I am travelling to Switzerland'),
( 'Ich bin gerade',  'am',  'Marktplatz',  'I am in the market place right now'),
( 'Ich bin gerade',  'in',  'der Apotheke',  'I am in the pharmacy right now'),
( 'Ich bin gerade',  'zu',  'Hause',  'I am at home right now'),
( 'Ich gehe jetzt',  'nach',  'Hause',  'I am going home now'),
('Ich nehme das Buch',  'aus',  'dem Regal',  'I take the book off the shelf'),
('Ich stelle das Glas',  'auf',  'den Tisch',  'I put the glass on the table'),
('Ich hänge die Lampe',  'über',  'den Esstisch',  'I hang the lamp over the dining table'),
('Die Lampe hängt',  'über',  'dem Esstisch',  'The lamp hangs over the dining table'),
('Ich setze mich',  'auf',  'das Sofa',  'I sit down on the sofa'),
('Ich fliege',  'ab',  'Frankfurt mit Lufthansa',  'I am flying from Frankfurt with Lufthansa'),
( 'Sie kommt',  'aus',  'Deutschland',  'She comes from Germany'),
( 'Die Katze springt',  'durch',  'das Fenster',  'The cat jumps through the window'),
( 'Die Familie sitzt',  'um',  'den Tisch',  'The family is sitting round the table'),
( 'Das Auto fuhr',  'gegen',  'den Baum',  'The car hit the tree'),
( 'Gehen Sie diese Straße',  'entlang',  'und biegen Sie am Ende links ab',  'Go along this street and turn left at the end'),
( 'Köln liegt',  'am',  'Rhein',  'Cologne is on the Rhine'),
( 'Das Kind versteckt sich',  'hinter',  'seiner Mutter',  'The child hides behind his mother'),
( 'Ich gehe jetzt',  'auf',  'die Bank',  'I am going to the bank now'),
( 'Der Schrank steht',  'neben',  'der Tür',  'The cupboard stands next to the door'),
( 'Meine Schwester woht im Haus',  'neben',  'der Kneipe',  'My sister lives in the house next to the pub'),
( 'Ich wohne lieber',  'außerhalb',  'der Stadt',  'I prefer to live outside the city'),
( 'Diese Fahrkarte ist nur',  'innerhalb',  'der Stadt gültig',  'This travel card is only valid within the city'),
( 'Wir fahren',  'über',  'Frankfurt nach Berlin',  'We are travelling via Frankfurt to Berlin'),
( 'Ein alter Baum steht',  'vor',  'dem Haus',  'An old tree stands in front of the house'),
( 'Das Rathaus liegt',  'zwischen',  'dem Park und dem Fluss',  'The town hall is between the park and the river')
;